language: python
before_install:
  - curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-3.3.1-64bit-static.tar.xz
  - tar Jxf ffmpeg-3.3.1-64bit-static.tar.xz
install:
  - pip install -r requirements.txt
script:
  - export PATH=$(readlink -f ffmpeg-3.3.1-64bit-static):$PATH
  - py.test
