language: python
before_install:
  - curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-3.3.1-64bit-static.tar.xz
  - tar Jxf ffmpeg-3.3.1-64bit-static.tar.xz
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.3
      env:
      - TOXENV=py33
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: pypy
      env:
      - TOXENV=pypy
install:
  - pip install tox
script:
  - export PATH=$(readlink -f ffmpeg-3.3.1-64bit-static):$PATH
  - tox -e $TOX_ENV
cache:
  directories:
    - .tox
